### ISSUE TITLE
Fix code scanning alert - Flask app is run in debug mode

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/cloud-run-microservice-template-python#113]
This is for local development. Production does not use the flask server. We should evaluate if we used this flag to improve the developer experience.

Tracking issue for:
- [x] https://github.com/GoogleCloudPlatform/cloud-run-microservice-template-python/security/code-scanning/1

**Comment by engelke** [comment]
Alert is false positive and has been dismissed.
