### ISSUE TITLE
Flask Microservice Mapped Domain not working with www

### ISSUE THREAD

**Issue by faizan170** [GoogleCloudPlatform/cloud-run-microservice-template-python#83]
I have deployed a flask web app on Google Cloud Run and mapped domain to that service. Domain is accessible without www. But when i use domain with www e.g (www.domain.com), it does not work
`This site can’t be reached`

**Comment by averikitsch** [comment]
Hi @faizan170, this issue queue is for the code within this repository. Please add this question to Stackoverflow or use the send feedback button on the [documentation page](https://cloud.google.com/run/docs/mapping-custom-domains).
